### ISSUE TITLE
segfaults in solve_1d.py

### ISSUE THREAD

**Issue by janoschpreuss** [UCL/dxss#66]
Hi,
I am observing segfaults when running `dxss/src/dxss/solve_1d.py` . The error message is as follows 

```
~/projects/dxss/src/dxss$ python3 solve_1d.py 
KSP Object: 1 MPI process
  type: gmres
    restart=1000, using Modified Gram-Schmidt Orthogonalization
    happy breakdown tolerance 1e-30
  maximum iterations=100000, initial guess is zero
  tolerances:  relative=1e-07, absolute=1e-07, divergence=10000.
  left preconditioning
  using DEFAULT norm type for convergence test
PC Object: 1 MPI process
  type: python
    Python: dxss.gmres.PreTimeMarchingImproved
  linear system matrix = precond matrix:
  Mat Object: 1 MPI process
    type: python
    rows=41216, cols=41216
        Python: dxss.space_time.FMatrix
GMRes iteration   0, residual = 4.46e-16
The convergence reason code is 3
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see https://petsc.org/release/faq/#valgrind and https://petsc.org/release/faq/
[0]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run 
[0]PETSC ERROR: to get more information on the crash.
[0]PETSC ERROR: Run with -malloc_debug to check if memory corruption is causing the crash.
Abort(59) on node 0 (rank 0 in comm 0): application called MPI_Abort(MPI_COMM_WORLD, 59) - process 
```
I am running the code in a fresh conda environment created as follows: 
```
conda activate fenicsx-env
conda install numpy scipy matplotlib sympy pytest
conda install conda-forge::meshio pypardiso gmsh python-gmsh
conda install -c conda-forge fenics-dolfinx==0.7.3 mpich pyvista
```
And then I install `dxh` and `dxss` with `pip install -e .`. 
Can anyone of you reproduce the error, or is this related to my machine? 
I think that the error is related to the GMRes solver from PETSc, because when I run my old code in this environment which uses NGSolve's GMRes it works just fine.

**Comment by matt-graham** [comment]
Hi @janoschpreuss. Can I check what OS you are on and the Python version in the environment you are using? With a Python 3.11 `conda` environment on Ubuntu 22.04 created using
```sh
conda create -n dxss -c conda-forge "python=3.11"
conda activate dxss 
conda install numpy scipy matplotlib sympy pytest
conda install conda-forge::meshio pypardiso gmsh python-gmsh
conda install -c conda-forge fenics-dolfinx==0.7.3 mpich pyvista
```
running `python src/dxss/solve_1d.py` from the root of the repository outputs
```
KSP Object: 1 MPI process
  type: gmres
    restart=1000, using Modified Gram-Schmidt Orthogonalization
    happy breakdown tolerance 1e-30
  maximum iterations=100000, initial guess is zero
  tolerances:  relative=1e-07, absolute=1e-07, divergence=10000.
  left preconditioning
  using DEFAULT norm type for convergence test
PC Object: 1 MPI process
  type: python
    Python: dxss.gmres.PreTimeMarchingImproved
  linear system matrix = precond matrix:
  Mat Object: 1 MPI process
    type: python
    rows=41216, cols=41216
        Python: dxss.space_time.FMatrix
GMRes iteration   0, residual = 4.46e-16
The convergence reason code is 3
elapsed time  19.310631275177002 seconds
t = 1, L2-error = 0.7071067811865475
L-infty-L2 error u =  0.7071067811865475
L-infty-L2 error u_t =  4.442882938158366
L2-L2 error u_t =  3.141592653589793
Memory usage in (Gb) =  0.702196
```
and exits without any segfaults (after manually closing the plot windows opened during execution).

**Comment by janoschpreuss** [comment]
Hi @matt-graham , thanks for your fast reply. I am on `Ubuntu 23.10` using `conda 24.3.0` and in the conda environment I have `Python 3.12.2`. 
I tried to create the environment as you suggested above pinning `python=3.11` . Unfortunately, I then run into some missing shared library error: 

```
(dxss) janosch@janosch-Precision-5820-Tower:~/projects/wave-uc-dg-repro$ python3
Python 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:53:32) [GCC 12.3.0] on linux
>>> from dolfinx import fem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/janosch/code/miniconda3/envs/dxss/lib/python3.11/site-packages/dolfinx/__init__.py", line 38, in <module>
    from dolfinx import common
  File "/home/janosch/code/miniconda3/envs/dxss/lib/python3.11/site-packages/dolfinx/common.py", line 11, in <module>
    from dolfinx import cpp as _cpp
ImportError: libtbb.so.2: cannot open shared object file: No such file or directory
```

Since the code apparently runs on your machine, could you do me a favour and run the script with the three different parameters `N=8`, `N=16` and `N=32`, where `N` is defined in ll.44 of the script?  I am asking, because the results above seems fishy to me. Firstly, the error is far too high for `N=32`. Secondly, if I understand the lines
```
GMRes iteration   0, residual = 4.46e-16
The convergence reason code is 3
```
correctly, GMRes appears to terminate immediately after the first iteration, which cannot be right. It should take more than a hundred iterations for `N=32`.

**Comment by janoschpreuss** [comment]
Some debugging progress:
I observed that the segfault does not occur when the plotting functionality is outcommented, i.e.
```
#ST.plot_error(u_sol, n_space=500, n_time_subdiv=20)
```
In this case I performed the convergence test suggested above (with `indicator_function=omega_ind_convex` ) and obtain:

```
N= 8 
GMRes iteration   0, residual = 6.53e-18
t = 1, L2-error = 0.7071067811865475

N = 16 
GMRes iteration   0, residual = 6.53e-18
t = 1, L2-error = 0.7071067811865475

N = 32 
GMRes iteration   0, residual = 4.46e-16
t = 1, L2-error = 0.7071067811865475
```
Unfortunately, this is complete nonsense. There is no convergence at all. 
Interestingly, the L2-errors are the same in all cases up to the last decimal digit.
This is probably as GMRes always terminates after one iteration which doesn't make sense.
The reference results obtained with the code in the repo wave_data_assimilation are: 

```
N = 8
GMRes iteration 29, residual = 6.060870963294271e-08
t = 1, L2-error = 0.004975339167422245

N = 16
GMRes iteration 54, residual = 9.059766713289366e-08
t = 1, L2-error = 0.0010727987676721596

N = 32
GMRes iteration 116, residual = 8.748934816490272e-08
t = 1, L2-error = 0.0002435082628974441
```
Here, the error reduces with increasing N at the expected rate and the GMRes iteration numbers increase as they should.
